# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maingui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.setings = QtWidgets.QHBoxLayout()
        self.setings.setObjectName("setings")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.setings.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.setings.addWidget(self.label)
        self.PopulationSpin = QtWidgets.QSpinBox(self.centralwidget)
        self.PopulationSpin.setMinimumSize(QtCore.QSize(50, 30))
        self.PopulationSpin.setObjectName("PopulationSpin")
        self.setings.addWidget(self.PopulationSpin)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.setings.addWidget(self.label_4)
        self.FoodSpin = QtWidgets.QSpinBox(self.centralwidget)
        self.FoodSpin.setMinimumSize(QtCore.QSize(40, 30))
        self.FoodSpin.setObjectName("FoodSpin")
        self.setings.addWidget(self.FoodSpin)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.setings.addWidget(self.label_5)
        self.TimeSpin = QtWidgets.QSpinBox(self.centralwidget)
        self.TimeSpin.setMinimumSize(QtCore.QSize(40, 30))
        self.TimeSpin.setObjectName("TimeSpin")
        self.setings.addWidget(self.TimeSpin)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.setings.addWidget(self.label_6)
        self.MutationRateSpin = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MutationRateSpin.sizePolicy().hasHeightForWidth())
        self.MutationRateSpin.setSizePolicy(sizePolicy)
        self.MutationRateSpin.setMinimumSize(QtCore.QSize(50, 30))
        self.MutationRateSpin.setMaximum(100)
        self.MutationRateSpin.setObjectName("MutationRateSpin")
        self.setings.addWidget(self.MutationRateSpin)
        self.btnBegin = QtWidgets.QPushButton(self.centralwidget)
        self.btnBegin.setObjectName("btnBegin")
        self.setings.addWidget(self.btnBegin)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.setings.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.setings)
        self.infos = QtWidgets.QHBoxLayout()
        self.infos.setObjectName("infos")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.infos.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.infos.addWidget(self.label_2)
        self.GeneretionText = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GeneretionText.sizePolicy().hasHeightForWidth())
        self.GeneretionText.setSizePolicy(sizePolicy)
        self.GeneretionText.setMinimumSize(QtCore.QSize(100, 30))
        self.GeneretionText.setMaximumSize(QtCore.QSize(100, 30))
        self.GeneretionText.setObjectName("GeneretionText")
        self.infos.addWidget(self.GeneretionText)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.infos.addWidget(self.label_3)
        self.MaxFitText = QtWidgets.QTextBrowser(self.centralwidget)
        self.MaxFitText.setMinimumSize(QtCore.QSize(100, 30))
        self.MaxFitText.setMaximumSize(QtCore.QSize(100, 30))
        self.MaxFitText.setObjectName("MaxFitText")
        self.infos.addWidget(self.MaxFitText)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.infos.addWidget(self.label_7)
        self.TimeText = QtWidgets.QTextBrowser(self.centralwidget)
        self.TimeText.setMaximumSize(QtCore.QSize(100, 30))
        self.TimeText.setObjectName("TimeText")
        self.infos.addWidget(self.TimeText)
        self.btnFinish = QtWidgets.QPushButton(self.centralwidget)
        self.btnFinish.setObjectName("btnFinish")
        self.infos.addWidget(self.btnFinish)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.infos.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.infos)
        self.graphs = QtWidgets.QHBoxLayout()
        self.graphs.setObjectName("graphs")
        self.grPlot = PlotWidget(self.centralwidget)
        self.grPlot.setMinimumSize(QtCore.QSize(500, 500))
        self.grPlot.setMaximumSize(QtCore.QSize(500, 500))
        self.grPlot.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.grPlot.setObjectName("grPlot")
        self.graphs.addWidget(self.grPlot)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.grPlot_3 = PlotWidget(self.centralwidget)
        self.grPlot_3.setMinimumSize(QtCore.QSize(300, 200))
        self.grPlot_3.setMaximumSize(QtCore.QSize(300, 200))
        self.grPlot_3.setObjectName("grPlot_3")
        self.verticalLayout_3.addWidget(self.grPlot_3, 0, QtCore.Qt.AlignHCenter)
        self.grPlot_2 = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grPlot_2.sizePolicy().hasHeightForWidth())
        self.grPlot_2.setSizePolicy(sizePolicy)
        self.grPlot_2.setMinimumSize(QtCore.QSize(300, 200))
        self.grPlot_2.setMaximumSize(QtCore.QSize(300, 200))
        self.grPlot_2.setObjectName("grPlot_2")
        self.verticalLayout_3.addWidget(self.grPlot_2, 0, QtCore.Qt.AlignHCenter)
        self.graphs.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.graphs)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Population:"))
        self.label_4.setText(_translate("MainWindow", "Food:"))
        self.label_5.setText(_translate("MainWindow", "Time by generation:"))
        self.label_6.setText(_translate("MainWindow", "Mutation rate (%):"))
        self.btnBegin.setText(_translate("MainWindow", "Start"))
        self.label_2.setText(_translate("MainWindow", "Generation:"))
        self.label_3.setText(_translate("MainWindow", "Max fit:"))
        self.label_7.setText(_translate("MainWindow", "Time:"))
        self.btnFinish.setText(_translate("MainWindow", "Finish"))

from pyqtgraph import PlotWidget
